### ISSUE TITLE
Song offset is wrong on low-end devices, until you restart the level from the pause menu

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/rd#91] opened 2023-11-12 04:45 UTC
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

@gwoobeast (discord)

### Summary

I've watched two of my friends stream rhythm doctor on discord, and while watching both of them, I noticed the offset for 5-2 seems wrong (from a few ms to nearly half a second) until they restart the level from the pause menu. One of them also says this has happened on 5-2N (she also says this has happened when she isn't streaming, so streaming shouldn't be causing this).

### Version

v0.14.0 (r30)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. On a lower-end device(?), start a level (maybe this only happens in 5-2 / 5-2N? I don't know)

### Expected Behavior

Song offset is okay, button inputs and sound effects are in rhythm with the music

### Observed Behavior

The offset is wrong throughout the whole level, until it is restarted

### Reproduction Rate

Often

**Comment by Satellite-7th-Beat-Games** [comment] 2024-04-26 03:12
duplicate of #49

**Closed by Satellite-7th-Beat-Games** 2024-04-26 03:12 UTC
Labels: Bug, Meta: Needs triage
