### ISSUE TITLE
3-3N AI synced beats don't work on some devices

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/rd#63] opened 2022-12-11 01:15 UTC
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

From steam community:
> For some reason, even though I'm hitting the beat and the flash lines up with the duet flash, the first two playable taps won't register, making it impossible to S-rank for me. I've tried closing the reopening the game, any solutions? (It is also possible that I am just being bad)

>
> Here is a clip for an example (Link should work this time): [https://medal.tv/games/rhythm-doctor/clips/LDWNffrcrhIQ6/d1337n1fIEYV?invite=cr-MSw1YW4sMTU3NTkxMzU5LA]

I cannot repeat the error on my device, however it is consistent between versions.

Link to original thread (https://steamcommunity.com/app/774181/discussions/1/3717188878655660449/?tscn=1670716363)

[Player (3).log](https://github.com/7thbeatgames/rd/files/10201284/Player.3.log)

### Version

r27 (Meet and Tweet), Live and Beta

### Operating System (OS)

Windows

### Platform

Steam

### Steps to Reproduce

Play 3-3N

### Expected Behavior

AI synced beats at the start can be hit by the player.

### Observed Behavior

Even with right timing, they are automatically missed.

### Reproduction Rate

Cannot reproduce on my machine.eeee

**Comment by notdonte** [comment] 2022-12-11 01:33
> I am running windows 10. My Pc has a RTX 2060 and a Ryzen 5 3600 CPU.

**Comment by huantianad** [comment] 2022-12-11 01:52
IIRC this is due to their p1 and p2 offsets being different, @RandomGuyJCI  and @giacomopc were working on it last time I checked, but for now the workaround is to set both offsets to the same value

**Comment by notdonte** [comment] 2022-12-11 02:46
I'll forward the workaround to the user, thanks.

**Comment by notdonte** [comment] 2022-12-11 04:13
The workaround worked for the user, does this already have an issue you can merge it with or should I just leave it open for now?

**Comment by RandomGuyJCI** [comment] 2022-12-11 15:45
Apologies, still haven't gotten around to fixing the bug yet! Marking as a duplicate of #57 for now

**Closed by RandomGuyJCI** 2022-12-11 15:45 UTC
Labels: Bug, Meta: Needs triage
